### ISSUE TITLE
Important TODO list

### ISSUE THREAD

**Issue by zachary62** [zachary62/JoinBoost#8]
Very important:

- [ ] **Add a Checker for the fact table and missing join keys:** Current JoinBoost assumes that there is a fact table user specified that has a many-to-one relationship along the path to all dimension tables, and there are no missing join keys. We eventually want to relax these assumptions. The first step is to check if these two assumptions are correct. We need more test cases for that.
- [ ]  For missing join keys, use semi-join.
- [ ] For a database with relations of the same attribute name, will this cause error?

For a many-to-one relationship, if it doesn't hold and there's a many-to-many between fact table and dimension table, we want to pre-aggregate the dimension table to make it many-to-one. For instance, if we have a weather report join with the fact table on date, but there are many reports per date, we want to compute a set of aggregations (e.g., mean, max, sum, min, std) for the weather result.  The pre-aggregation result could be stored lazily as a view, and eagerly as a table. 
- [x] **naming conflict with semi-ring**: currently, the semi-ring uses "c" for count and "s" for sum. For tables already have attributes "s" and "c", this could cause trouble. We need to (1) check if these names are already used (2) if so, replaces it with names unused.
- [x] **Support Pandas**: Pandas Dataframe is a popular machine learning data structure and could be natively supported through DuckDB relational API. However, it is currently not fully supported and tested. We want to build the full executor for Pandas Dataframe.
- [ ] **Support Prediction**: Implement a predict function that follows a similar API as LightGBM. Current JoinBoost only predicts the rmse over the **full join** which is against the purpose of factorized learning. We want to support prediction when the user gives only the fact table. There are different ways to predict based on fact tables (materialize join then select columns, or directly select by semi-join). We want to explore the design space. Check target variable in the fact table.
- [ ] Preprocessor for the model. add test to check if the table has been cleanly deleted, and not other tables. make sure it doesn't rewrite. add warning. Check no cycle, no name conflicts, there is a single fact table.  outer join first for missing join keys?

Good to have:
- [ ] Support classification and different criteria as in LightGBM. The algorithms have been studied, but not implemented.
- [ ] Support automatic feature engineering. E.g., for date column, extract whether it's holiday. whether it's weekend. Also, support augmentation from https://github.com/upgini/upgini This would be important for Kaggle competition as we can potentially show better model performance.
- [ ] Support visualization of the tree, as in https://scikit-learn.org/stable/modules/generated/sklearn.tree.plot_tree.html
- [ ] Support parameters from LightGBM. Some parameters that are easy to add are L1, and L2 regularization. The early stop is also not hard. 
- [ ] Support more databases. For most databases, column updates will be the bottleneck, so focus on random forests.
- [ ] CatBoost has some fancy techniques to deal with categorical attributes. We should also use them if they are empirically useful.
- [ ] Optimize the deep tree. For now, if the tree depth is large (>5), joinboost is slow. I'm not sure why and it is interesting to investigate.
- [ ] Dictionary encoding: replace string field (expensive) with an integer. Replace composite join keys with single join keys. store the mapping as a table somewhere.
- [ ] Join the same table twice (e.g., data, self-join) and deal with the table name ambiguity
- [ ] EBM
- [ ] Integration with dbt
- [ ] Figure out how the model is stored. Make the format compatible.

**Comment by zachary62** [comment]
For a large dimension table, we shall sort by the dimension key to improve performance, which triggers merge sort join.

**Comment by zachary62** [comment]
Sample with/without replacement

**Comment by zachary62** [comment]
To build JoinBoost Python library:
